import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    channels: {
      public: [
        {
          title: "Channel 1",
          id: 1,
          type: "public",
          description: "This is the description for Channel 1.",
        },
        {
          title: "Channel 2",
          id: 2,
          type: "public",
          description: "This is the description for Channel 2.",
        },
      ],
      personal: [
        {
          title: "Channel 3",
          id: 3,
          type: "personal",
          description: "This is the description for Channel 3.",
        },
        {
          title: "Channel 4",
          id: 4,
          type: "personal",
          description: "This is the description for Channel 4.",
        },
      ],
      group: [
        {
          title: "Channel 5",
          id: 5,
          type: "group",
          description: "This is the description for Channel 5.",
        },
        {
          title: "Channel 6",
          id: 6,
          type: "group",
          description: "This is the description for Channel 6.",
        },
      ],
    },
    channel_reports: [
      {
        id: 1,
        title: "Report 1",
        data_set: "Data Set 1",
        channel: "Channel 1",
        channel_id: 1,
        date: "June 15, 2021",
        tags: ["Employee Data", "Company Reports"],
        chart_type: "line",
      },
      {
        id: 2,
        title: "Report 2",
        data_set: "Data Set 2",
        channel: "Channel 2",
        channel_id: 2,
        date: "June 16, 2021",
        tags: ["Monthly", "Sales"],
        chart_type: "pie",
      },
      {
        id: 3,
        title: "Report 3",
        data_set: "Data Set 3",
        channel: "Channel 1",
        channel_id: 1,
        date: "June 17, 2021",
        tags: ["Weekly", "Sales"],
        chart_type: "bar",
      },
      {
        id: 4,
        title: "Report 4",
        data_set: "Data Set 4",
        channel: "Channel 2",
        channel_id: 2,
        date: "June 10, 2021",
        tags: ["Employee Data"],
        chart_type: "donut",
      },
      {
        id: 5,
        title: "Report 5",
        data_set: "Data Set 5",
        channel: "Channel 1",
        channel_id: 1,
        date: "June 15, 2021",
        tags: ["Company Reports", "Weekly"],
        chart_type: "table",
      },
      {
        id: 6,
        title: "Report 6",
        data_set: "Data Set 6",
        channel: "Channel 2",
        channel_id: 2,
        date: "June 18, 2021",
        tags: ["Performance", "Sales", "Monthly"],
        chart_type: "curve",
      },

      {
        id: 7,
        title: "Report 7",
        data_set: "Data Set 7",
        channel: "Channel 3",
        channel_id: 3,
        date: "June 1, 2021",
        tags: ["Performance", "Sales", "Monthly"],
        chart_type: "curve",
      },
      {
        id: 8,
        title: "Report 8",
        data_set: "Data Set 8",
        channel: "Channel 4",
        channel_id: 4,
        date: "June 3, 2021",
        tags: ["Sales", "Monthly"],
        chart_type: "donut",
      },
      {
        id: 9,
        title: "Report 9",
        data_set: "Data Set 9",
        channel: "Channel 3",
        channel_id: 3,
        date: "June 3, 2021",
        tags: ["Sales", "Weekly"],
        chart_type: "pie",
      },

      {
        id: 10,
        title: "Report 10",
        data_set: "Data Set 10",
        channel: "Channel 5",
        channel_id: 5,
        date: "June 29, 2021",
        tags: ["Employee Data", "Monthly"],
        chart_type: "pie",
      },
    ],
    active_data_set: {},
    data_sets: [],
    active_report: {},
    reports: [],
    latest_reports: {
      public: [
        {
          id: 1,
          title: "Report 1",
          data_set: "Data Set 1",
          channel: "Channel 1",
          channel_id: 1,
          date: "June 15, 2021",
          tags: ["Employee Data", "Company Reports"],
          chart_type: "line",
        },
        {
          id: 2,
          title: "Report 2",
          data_set: "Data Set 2",
          channel: "Channel 2",
          channel_id: 2,
          date: "June 16, 2021",
          tags: ["Monthly", "Sales"],
          chart_type: "pie",
        },
        {
          id: 3,
          title: "Report 3",
          data_set: "Data Set 3",
          channel: "Channel 1",
          channel_id: 1,
          date: "June 17, 2021",
          tags: ["Weekly", "Sales"],
          chart_type: "bar",
        },
        {
          id: 4,
          title: "Report 4",
          data_set: "Data Set 4",
          channel: "Channel 2",
          channel_id: 2,
          date: "June 10, 2021",
          tags: ["Employee Data"],
          chart_type: "donut",
        },
        {
          id: 5,
          title: "Report 5",
          data_set: "Data Set 5",
          channel: "Channel 1",
          channel_id: 1,
          date: "June 15, 2021",
          tags: ["Company Reports", "Weekly"],
          chart_type: "table",
        },
        {
          id: 6,
          title: "Report 6",
          data_set: "Data Set 6",
          channel: "Channel 2",
          channel_id: 2,
          date: "June 18, 2021",
          tags: ["Performance", "Sales", "Monthly"],
          chart_type: "curve",
        },
      ],
      personal: [
        {
          id: 7,
          title: "Report 7",
          data_set: "Data Set 7",
          channel: "Channel 3",
          channel_id: 3,
          date: "June 1, 2021",
          tags: ["Performance", "Sales", "Monthly"],
          chart_type: "curve",
        },
        {
          id: 8,
          title: "Report 8",
          data_set: "Data Set 8",
          channel: "Channel 4",
          channel_id: 4,
          date: "June 3, 2021",
          tags: ["Sales", "Monthly"],
          chart_type: "donut",
        },
        {
          id: 9,
          title: "Report 9",
          data_set: "Data Set 9",
          channel: "Channel 3",
          channel_id: 3,
          date: "June 3, 2021",
          tags: ["Sales", "Weekly"],
          chart_type: "pie",
        },
      ],
      group: [
        {
          id: 10,
          title: "Report 10",
          data_set: "Data Set 10",
          channel: "Channel 5",
          channel_id: 5,
          date: "June 29, 2021",
          tags: ["Employee Data", "Monthly"],
          chart_type: "pie",
        },
      ],
    },
  },
  actions: {},
  mutations: {},
  getters: {
    channels: (state) => state.channels,
    channelReports: (state) => state.channel_reports,
    activeDataSet: (state) => state.active_data_set,
    dataSets: (state) => state.data_sets,
    activeReport: (state) => state.active_report,
    reports: (state) => state.reports,
    latestReports: (state) => state.latest_reports,
  },
  modules: {},
});
